title: Tom Meagher
description: "Making Internet things."
url: "http://meagher.co"
author: "Tom Meagher"
keywords: "tom,tomfme,meagher,code,design,startups,technology,tech,design"
github: tmm
twitter: tomfme
email: tom@meagher.co

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]

permalink: pretty
timezone: America/New_York

plugins: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
