title: Tom Meagher
description: "I love making things—often with code, pixels, and words."
url: "http://meagher.co"
author: "Tom Meagher"
keywords: "tom,meagher,code,design,startups,start ups,technology,tech"

github: tmm
twitter: tomfme
email: tom@meagher.co

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore", "tmm.sublime-project"]
include: []

permalink: pretty
paginate: 5
paginate_path: "blog/:num"
timezone: America/New_York

gems: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

links:
  - name: home
    url: /
  - name: blog
    url: /blog/
