# Site settings
title: Tom Meagher
email: thom.meagher@gmail.com
description: "I love making things—often with code, pixels, and words."
url: "http://meagher.co"
author: "Tom Meagher"
keywords: "tom,meagher,code,design,startups,start ups,technology,tech,"
github: tmm

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: []

# Outputting
timezone: America/New_York
permalink: pretty

# Plugins
gems: [jekyll-paginate]

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
paginate: 10
paginate_path: "blog/num"