# Site settings
title: Thomas Meagher
description: "love what you do."
url: "http://thomasmeagher.com"
author: "Thomas Meagher"
keywords: "Thomas,Meagher,startups,iOS,developer,innovate"

exclude: ["readme.md", "CNAME"]
include: []
timezone: America/New_York
