# Site settings
title: Tom Meagher
email: thom.meagher@gmail.com
description: ""
url: "http://meagher.co"
author: "Tom Meagher"
keywords: "Tom,Meagher,code,design,start ups,technology"

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: []

# Outputting
timezone: America/New_York
permalink: pretty

# Plugins
gems: [jekyll-paginate]

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
paginate: 10
paginate_path: "blog/page:num"

# Variables
twitter: thomasmeagher
github: tmm