# Site Settings
title: Thomas Meagher
description: "love what you do."
url: "http://thomasmeagher.com"
author: "Thomas Meagher"
keywords: "Thomas,Meagher,Tom,startups"

# Setup
paginate: 5
paginate_path: "blog/page:num"

# Conversion
markdown: kramdown
highlighter: pygments

# Handling Reading
exclude: ["readme.md", "CNAME"]
include: []

# Outputting
timezone: America/New_York
permalink: pretty