title: Tom Meagher
description: "Solving problems with data and code."
url: "http://meagher.co"
author: "Tom Meagher"
keywords: "tom,tomfme,meagher,code,design,startups,start ups,startups,technology,tech,data,design"

github: tmm
twitter: tomfme
email: tom@meagher.co

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore", "tmm.sublime-project", "sketch"]
include: []

permalink: pretty
timezone: America/New_York

gems: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"